[build-system]
requires = [
    "setuptools>=61,<82",
    "setuptools-scm[simple]>=9.2",
]
build-backend = "setuptools.build_meta"

[project]
name = "minervachem-lamel"
dynamic = ["version"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Software Development :: Libraries",
]
description = "LAMEL add-on for MinervaChem"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "minervachem>0.0.2,<1",
    "xgboost>=3.2.0,<4",
]

[tool.setuptools]
packages = ["lamel"]
package-dir = { lamel = "." }

[tool.setuptools_scm]
root = ".."

[tool.setuptools_scm.tag]
prefix = "lamel-v"
strict = true
