[build-system]
requires = [
    "setuptools>=61,<82",
    "setuptools-scm[simple]>=9.2",
]
build-backend = "setuptools.build_meta"

[project]
name = "minervachem"
dynamic = ["version"]
description = "Machine learning for Cheminformatics"
readme = "README.md"
requires-python = ">=3.11,<3.12"
license = { text = "BSD 3-Clause License" }

authors = [
    { name = "Michael Frederick Tynes", email = "mtynes@lanl.gov" },
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Software Development :: Libraries",
]

dependencies = [
    "numpy",
    "scipy",
    "pandas",
    "scikit-learn",
    "tqdm",
    "sigfig",
    "matplotlib",
    "pillow",
    "imageio",
    "lightgbm",
    "flaml",
    "networkx",
    "cairosvg",
    "jupyterlab",
    "ipywidgets",
    "seaborn",
    "joblib>=1.3.0",
    "svglib",
    "sparse>=0.13.0",
    "dask",
    "distributed",
    "rdkit>2023.9.6,<2026.0",
    "buhito<1",
    "reportlab",
    "architector",
]

[project.urls]
Homepage = "https://github.com/lanl/minervachem"
"Bug Tracker" = "https://github.com/lanl/minervachem/issues"
"Source Code" = "https://github.com/lanl/minervachem"

[project.optional-dependencies]
dev = [
    "pytest>=6.2.4,<10.0",
    "coverage>=5.5,<8.0",
    "PyTDC",
    "setuptools>=61,<82",
    "xgboost",
]

[tool.pytest.ini_options]
addopts = "-v"
testpaths = ["tests"]

[tool.setuptools.packages.find]
where = ["."]
include = ["minervachem*"]

[tool.setuptools.package-data]
"minervachem.mcts.sa_score" = ["fpscores.pkl.gz", "LICENSE", "README.md"]
